import { useMemo,useState } from 'react';
import { Alert,App,Button,Card,Descriptions,Form,Input,InputNumber,Modal,Select,Space,Table,Tag } from 'antd';
import { DownloadOutlined,PlusOutlined,SearchOutlined } from '@ant-design/icons';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../../../api/client';
import { useAuth } from '../../auth/context/AuthContext';
import type { Option,Page,Quotation,Template } from '../types';
import { apiErrorCode,apiFormErrors,quotationPermissions,requiresUnsavedConfirmation,sitesForParty,validateQuotationEditor,type QuotationEditor as Editor } from '../quotationForm';

const rental=[{value:'PER_PIECE_PER_DAY',label:'Per piece per day'},{value:'PLATE_AREA_PER_DAY',label:'Plate area per day'},{value:'SCAFFOLD_AREA_PER_DAY',label:'Scaffold area per day'},{value:'PLOT_AREA_PER_DAY',label:'Plot area per day'},{value:'FIXED_RATE',label:'Fixed rate'},{value:'SLAB_BASED',label:'Slab based'}];
const money=(v?:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v??0);
export function QuotationsPage(){
  const {modal,message}=App.useApp(),{user}=useAuth(),roles=user?.roles??[],{isAdmin,canWrite}=quotationPermissions(roles),qc=useQueryClient();
  const [search,setSearch]=useState(''),[status,setStatus]=useState<string|undefined>(),[open,setOpen]=useState(false),[editing,setEditing]=useState<Quotation|null>(null),[selected,setSelected]=useState<Quotation|null>(null);
  const [form]=Form.useForm<Editor>();const partyId=Form.useWatch('partyId',form);const watched=Form.useWatch([],form);
  const quotations=useQuery({queryKey:['quotations',search,status],queryFn:async()=>(await apiClient.get<Page<Quotation>>('/quotations',{params:{search,status,size:50,sort:'quotationDate,desc'}})).data});
  const templates=useQuery({queryKey:['quotation-templates-active'],queryFn:async()=>(await apiClient.get<Page<Template>>('/quotation-templates',{params:{active:true,size:100}})).data.content});
  const parties=useQuery({queryKey:['parties-options'],queryFn:async()=>(await apiClient.get<Page<Option>>('/parties',{params:{active:true,size:200}})).data.content});
  const sites=useQuery({queryKey:['sites-options'],queryFn:async()=>(await apiClient.get<Page<Option>>('/sites',{params:{size:200}})).data.content});
  const items=useQuery({queryKey:['items-options'],queryFn:async()=>(await apiClient.get<Page<Option>>('/items',{params:{active:true,size:500}})).data.content});
  const save=useMutation({mutationFn:async(v:Editor)=>editing?(await apiClient.put(`/quotations/${editing.id}`,{...v,version:editing.version})).data:(await apiClient.post('/quotations',v)).data,
    onSuccess:(q:Quotation)=>{message.success(`Saved ${q.quotationNumber}`);setOpen(false);void qc.invalidateQueries({queryKey:['quotations']});},onError:(error:unknown)=>{const fields=apiFormErrors(error);if(fields.length)form.setFields(fields);message.error(apiErrorCode(error)==='OPTIMISTIC_LOCK_CONFLICT'?'This quotation was changed by another user. Reload and try again.':'Unable to save quotation.');}});
  const action=useMutation({mutationFn:async({q,name,reason}:{q:Quotation;name:string;reason?:string})=>(await apiClient.post(`/quotations/${q.id}/${name}`,reason?{reason}:undefined)).data,
    onSuccess:()=>void qc.invalidateQueries({queryKey:['quotations']})});
  const defaults=():Editor=>({quotationTemplateId:0,partyId:0,siteId:0,quotationDate:new Date().toISOString().slice(0,10),validUntil:new Date(Date.now()+30*86400000).toISOString().slice(0,10),rentalType:'PER_PIECE_PER_DAY',discountType:'NONE',discountValue:0,cgstRate:9,sgstRate:9,igstRate:0,transportCharge:0,loadingCharge:0,unloadingCharge:0,otherCharge:0,roundOff:0,securityDeposit:0,items:[{itemId:0,quantity:1,rate:0,rentalType:'PER_PIECE_PER_DAY'}]});
  const edit=(q?:Quotation)=>{setEditing(q??null);form.setFieldsValue(q?{...q}:defaults());setOpen(true);};
  const confirm=(q:Quotation,name:string,needsReason=false)=>{let reason='';modal.confirm({title:`${name} ${q.quotationNumber}?`,content:needsReason?<Input.TextArea placeholder="Reason is required" onChange={e=>reason=e.target.value}/>:undefined,onOk:()=>{if(needsReason&&!reason.trim()){message.error('Reason is required');return Promise.reject();}return action.mutateAsync({q,name,reason});}});};
  const download=async(q:Quotation)=>{const r=await apiClient.get(`/quotations/${q.id}/pdf`,{responseType:'blob'});const url=URL.createObjectURL(r.data as Blob);const a=document.createElement('a');a.href=url;a.download=`quotation-${q.quotationNumber.replaceAll('/','-')}.pdf`;a.click();URL.revokeObjectURL(url);};
  const estimate=useMemo(()=>{const v=watched; if(!v)return 0;const sub=(v.items??[]).reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.rate)||0),0);const discount=v.discountType==='PERCENTAGE'?sub*(Number(v.discountValue)||0)/100:v.discountType==='FIXED'?Number(v.discountValue)||0:0;const taxable=sub-discount+(Number(v.transportCharge)||0)+(Number(v.loadingCharge)||0)+(Number(v.unloadingCharge)||0)+(Number(v.otherCharge)||0);return taxable*(1+((Number(v.cgstRate)||0)+(Number(v.sgstRate)||0)+(Number(v.igstRate)||0))/100)+(Number(v.roundOff)||0);},[watched]);
  return <div className="page-stack"><div className="page-header-container"><div><h1 className="page-heading">Quotations</h1><p className="page-description">Prepare, issue and approve commercial offers without reserving stock.</p></div>{canWrite&&<Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit()}>Add quotation</Button>}</div>
    <Card className="premium-card"><Space className="filters-bar" wrap><Input prefix={<SearchOutlined/>} allowClear placeholder="Search quotations" value={search} onChange={e=>setSearch(e.target.value)}/><Select allowClear placeholder="All statuses" style={{width:170}} onChange={setStatus} options={['DRAFT','SENT','APPROVED','REJECTED','EXPIRED','CANCELLED'].map(v=>({value:v,label:v}))}/></Space>
      <Table rowKey="id" loading={quotations.isLoading} dataSource={quotations.data?.content} scroll={{x:1100}} columns={[
        {title:'Quotation',dataIndex:'quotationNumber'},{title:'Party',dataIndex:'partyName'},{title:'Site',dataIndex:'siteName'},{title:'Date',dataIndex:'quotationDate'},{title:'Total',dataIndex:'grandTotal',render:money},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={v==='APPROVED'?'success':v==='REJECTED'||v==='CANCELLED'?'error':'processing'}>{v}</Tag>},
        {title:'Actions',render:(_:unknown,q:Quotation)=><QuotationActionButtons q={q} isAdmin={isAdmin} canWrite={canWrite} onView={()=>setSelected(q)} onEdit={()=>edit(q)} onAction={(name,reason)=>confirm(q,name,reason)} onPdf={()=>void download(q)}/>},
      ]}/></Card>
    <Modal open={open} title={editing?'Edit quotation':'New quotation'} width={1000} onCancel={()=>{if(requiresUnsavedConfirmation(form.isFieldsTouched()))modal.confirm({title:'Discard unsaved changes?',onOk:()=>setOpen(false)});else setOpen(false);}} onOk={()=>form.submit()} confirmLoading={save.isPending}>
      <Form form={form} layout="vertical" onFinish={v=>{const errors=validateQuotationEditor(v,sites.data??[]);if(errors.length){form.setFields(errors);return;}save.mutate(v);}}><div className="master-form-grid">
        <Form.Item name="quotationTemplateId" label="Template" rules={[{required:true}]}><Select options={(templates.data??[]).map(t=>({value:t.id,label:`${t.templateCode} — ${t.name}`}))}/></Form.Item>
        <Form.Item name="partyId" label="Party" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(parties.data??[]).map(p=>({value:p.id,label:p.legalName}))} onChange={()=>form.setFieldValue('siteId',undefined)}/></Form.Item>
        <Form.Item name="siteId" label="Site" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={sitesForParty(sites.data??[],partyId).map(s=>({value:s.id,label:`${s.siteCode} — ${s.siteName}`}))}/></Form.Item>
        <Form.Item name="rentalType" label="Rental type" rules={[{required:true}]}><Select options={rental}/></Form.Item>
        <Form.Item name="quotationDate" label="Quotation date" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="validUntil" label="Valid until" rules={[{required:true}]}><Input type="date"/></Form.Item>
        <Form.Item name="discountType" label="Discount"><Select options={['NONE','PERCENTAGE','FIXED'].map(value=>({value,label:value}))}/></Form.Item><Money name="discountValue" label="Discount value"/>
        <Money name="cgstRate" label="CGST %"/><Money name="sgstRate" label="SGST %"/><Money name="igstRate" label="IGST %"/>
        <Money name="transportCharge" label="Transport"/><Money name="loadingCharge" label="Loading"/><Money name="unloadingCharge" label="Unloading"/><Money name="otherCharge" label="Other charge"/><Money name="roundOff" label="Round off" signed/><Money name="securityDeposit" label="Security deposit"/>
        <Form.Item className="master-form-wide" name="terms" label="Terms"><Input.TextArea rows={3}/></Form.Item><Form.Item className="master-form-wide" name="notes" label="Notes"><Input.TextArea/></Form.Item>
      </div><QuotationItemRows items={items.data??[]}/>
      <Alert type="info" showIcon message={`Estimated grand total: ${money(estimate)}`} description="The backend recalculates and stores the authoritative total."/></Form>
    </Modal>
    <Modal open={!!selected} title={selected?.quotationNumber} footer={null} onCancel={()=>setSelected(null)} width={850}>{selected&&<><Descriptions bordered column={2} items={[{key:'party',label:'Party',children:selected.partyName},{key:'site',label:'Site',children:selected.siteName},{key:'template',label:'Template',children:selected.quotationTemplateName},{key:'total',label:'Grand total',children:money(selected.grandTotal)},{key:'tax',label:'Total GST',children:money(selected.totalTax)},{key:'deposit',label:'Security deposit',children:money(selected.securityDeposit)}]}/><Table style={{marginTop:16}} pagination={false} rowKey={(i)=>i.id??i.itemId} dataSource={selected.items} columns={[{title:'Code',dataIndex:'itemCodeSnapshot'},{title:'Item',dataIndex:'itemNameSnapshot'},{title:'Qty',dataIndex:'quantity'},{title:'Rate',dataIndex:'rate',render:money},{title:'Amount',dataIndex:'amount',render:money}]}/></>}</Modal>
  </div>;
}
export function QuotationActionButtons({q,isAdmin,canWrite,onView,onEdit,onAction,onPdf}:{q:Quotation;isAdmin:boolean;canWrite:boolean;onView:()=>void;onEdit:()=>void;onAction:(name:string,needsReason?:boolean)=>void;onPdf:()=>void}){
  return <Space wrap><Button onClick={onView}>View</Button>{canWrite&&q.status==='DRAFT'&&<Button onClick={onEdit}>Edit</Button>}{canWrite&&q.status==='DRAFT'&&<Button onClick={()=>onAction('send')}>Send</Button>}{isAdmin&&q.status==='SENT'&&<Button onClick={()=>onAction('approve')}>Approve</Button>}{isAdmin&&q.status==='SENT'&&<Button danger onClick={()=>onAction('reject',true)}>Reject</Button>}{isAdmin&&['DRAFT','SENT'].includes(q.status)&&<Button danger onClick={()=>onAction('cancel',true)}>Cancel</Button>}{canWrite&&<Button onClick={()=>onAction('clone')}>Clone</Button>}<Button icon={<DownloadOutlined/>} onClick={onPdf}>PDF</Button></Space>;
}
export function QuotationItemRows({items}:{items:Option[]}){
  return <Form.List name="items">{(fields,{add,remove})=><div className="commercial-lines"><Space><strong>Items</strong><Button onClick={()=>add({quantity:1,rate:0,rentalType:'PER_PIECE_PER_DAY'})}>Add line</Button></Space>{fields.map(({key,name})=><Space key={key} align="start" wrap><Form.Item name={[name,'itemId']} label="Item" rules={[{required:true}]}><Select style={{width:260}} showSearch optionFilterProp="label" options={items.map(i=>({value:i.id,label:`${i.itemCode} — ${i.itemName}`}))}/></Form.Item><Form.Item name={[name,'quantity']} label="Quantity" rules={[{required:true,type:'number',min:0.0001}]}><InputNumber min={0.0001}/></Form.Item><Form.Item name={[name,'rate']} label="Rate" rules={[{required:true,type:'number',min:0}]}><InputNumber min={0}/></Form.Item><Form.Item name={[name,'rentalType']} label="Rental type"><Select style={{width:190}} options={rental}/></Form.Item><Form.Item name={[name,'area']} label="Area"><InputNumber min={0}/></Form.Item><Form.Item name={[name,'weight']} label="Weight"><InputNumber min={0}/></Form.Item><Button danger type="text" onClick={()=>remove(name)} disabled={fields.length===1}>Remove</Button></Space>)}</div>}</Form.List>;
}
function Money({name,label,signed=false}:{name:keyof Editor;label:string;signed?:boolean}){return <Form.Item name={name} label={label} rules={[{required:true}]}><InputNumber min={signed?undefined:0} style={{width:'100%'}}/></Form.Item>;}
