import {useState} from 'react';
import {App,Button,Card,Descriptions,Empty,Form,Input,InputNumber,Modal,Select,Space,Table,Tag} from 'antd';
import {DownloadOutlined,SearchOutlined,SwapOutlined} from '@ant-design/icons';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '../../../api/client';
import {useAuth} from '../../auth/context/AuthContext';
import {FormDrawer} from '../../../components/FormDrawer';
import type {Quotation} from '../../quotation/types';
import type {Agreement,AgreementTemplate,Page} from '../types';

type Editor=Pick<Agreement,'agreementDate'|'effectiveDate'|'expiryDate'|'billingCycle'|'customBillingCycleDays'|'gracePeriodDays'|'minimumBillingDays'|'securityDeposit'|'terms'|'notes'|'items'>;
const money=(v?:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(v??0);
export function AgreementsPage(){
 const {user}=useAuth(),roles=user?.roles??[],admin=roles.includes('ROLE_ADMIN'),operations=roles.includes('ROLE_OPERATIONS'),canWrite=admin||operations;
 const {modal,message}=App.useApp(),qc=useQueryClient(),[search,setSearch]=useState(''),[status,setStatus]=useState<string>(),[selected,setSelected]=useState<Agreement>(),[editing,setEditing]=useState<Agreement>(),[convertOpen,setConvertOpen]=useState(false);const[form]=Form.useForm<Editor>();const[convertForm]=Form.useForm();
 const agreements=useQuery({queryKey:['agreements',search,status],queryFn:async()=>(await apiClient.get<Page<Agreement>>('/agreements',{params:{search,status,size:50,sort:'id,desc'}})).data});
 const approved=useQuery({queryKey:['approved-quotations'],queryFn:async()=>(await apiClient.get<Page<Quotation>>('/quotations',{params:{status:'APPROVED',size:200}})).data.content,enabled:canWrite});
 const templates=useQuery({queryKey:['agreement-templates'],queryFn:async()=>(await apiClient.get<AgreementTemplate[]>('/agreement-templates')).data,enabled:canWrite});
 const refresh=()=>{void qc.invalidateQueries({queryKey:['agreements']});void qc.invalidateQueries({queryKey:['approved-quotations']});void qc.invalidateQueries({queryKey:['quotations']});};
 const convert=useMutation({mutationFn:async(v:{quotationId:number;templateId?:number;effectiveDate:string;expiryDate?:string;securityDeposit:number;notes?:string})=>{const{quotationId,...body}=v;return(await apiClient.post<Agreement>(`/agreements/from-quotation/${quotationId}`,body)).data;},onSuccess:a=>{message.success(`Created ${a.agreementNumber}`);setConvertOpen(false);convertForm.resetFields();setSelected(a);refresh();},onError:(e:unknown)=>message.error(apiMessage(e))});
 const save=useMutation({mutationFn:async(v:Editor)=>(await apiClient.put<Agreement>(`/agreements/${editing?.id}`,{...v,version:editing?.version})).data,onSuccess:a=>{message.success('Agreement updated');setEditing(undefined);setSelected(a);refresh();},onError:()=>message.error('Unable to save. Reload if another user changed this agreement.')});
 const transition=useMutation({mutationFn:async({a,name,reason}:{a:Agreement;name:string;reason?:string})=>(await apiClient.post<Agreement>(`/agreements/${a.id}/${name}`,reason?{reason}:undefined)).data,onSuccess:a=>{message.success(`Agreement is ${a.status}`);setSelected(a);refresh();},onError:(e:unknown)=>message.error(apiMessage(e))});
 const act=(a:Agreement,name:string,reason=false)=>{let value='';modal.confirm({title:`${label(name)} ${a.agreementNumber}?`,content:reason?<Input.TextArea data-testid={`${name}-reason`} placeholder="Reason is required" onChange={e=>value=e.target.value}/>:undefined,onOk:()=>{if(reason&&!value.trim()){message.error('Reason is required');return Promise.reject();}return transition.mutateAsync({a,name,reason:value});}});};
 const edit=(a:Agreement)=>{setEditing(a);form.setFieldsValue({agreementDate:a.agreementDate,effectiveDate:a.effectiveDate,expiryDate:a.expiryDate,billingCycle:a.billingCycle,customBillingCycleDays:a.customBillingCycleDays,gracePeriodDays:a.gracePeriodDays,minimumBillingDays:a.minimumBillingDays,securityDeposit:a.securityDeposit,terms:a.terms,notes:a.notes,items:a.items});};
 const download=async(a:Agreement)=>{const r=await apiClient.get(`/agreements/${a.id}/document`,{responseType:'blob'});const url=URL.createObjectURL(r.data as Blob);const link=document.createElement('a');link.href=url;link.download=a.generatedFilename??`agreement-${a.agreementNumber.replaceAll('/','-')}.pdf`;link.click();URL.revokeObjectURL(url);};
 return <div className="page-stack" data-testid="agreements-page"><div className="page-header-container"><div><h1 className="page-heading">Agreements</h1><p className="page-description">Convert approved quotations into controlled, snapshot-backed agreements.</p></div>{canWrite&&<Button type="primary" icon={<SwapOutlined/>} data-testid="convert-agreement" onClick={()=>setConvertOpen(true)}>Convert quotation</Button>}</div>
 <Card className="premium-card agreement-card"><Space className="filters-bar agreement-toolbar" wrap><Input className="agreement-search" prefix={<SearchOutlined/>} placeholder="Search agreements" allowClear value={search} onChange={e=>setSearch(e.target.value)}/><Select className="agreement-status-filter" allowClear placeholder="All statuses" onChange={setStatus} options={['DRAFT','READY_FOR_REVIEW','ACTIVE','EXPIRED','TERMINATED','CLOSED','CANCELLED'].map(value=>({value,label:value.replaceAll('_',' ')}))}/></Space>
 {agreements.isLoading||(agreements.data?.content.length??0)>0?<Table className="agreement-table" rowKey="id" loading={agreements.isLoading} dataSource={agreements.data?.content} pagination={{hideOnSinglePage:true}} columns={[
  {title:'Agreement',dataIndex:'agreementNumber',width:150},{title:'Source quotation',dataIndex:'sourceQuotationNumber',width:160},{title:'Party',dataIndex:'partyName'},{title:'Site',render:(_:unknown,a:Agreement)=>`${a.siteCode} — ${a.siteName}`},{title:'Effective',dataIndex:'effectiveDate',width:110},{title:'Expiry',dataIndex:'expiryDate',width:110},{title:'Status',dataIndex:'status',width:120,render:(s:string)=><Tag className={`agreement-status agreement-status-${s.toLowerCase()}`}>{s.replaceAll('_',' ')}</Tag>},
  {title:'Actions',width:100,fixed:'right',render:(_:unknown,a:Agreement)=><AgreementActions agreement={a} admin={admin} operations={operations} onView={()=>setSelected(a)} onEdit={()=>edit(a)} onAction={(n,r)=>act(a,n,r)} onDownload={()=>void download(a)}/>}
 ]}/>:<div className="agreement-empty"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={<div><strong>No agreements yet</strong><span>Convert an approved quotation to create your first agreement.</span></div>}/>{canWrite&&<Button type="primary" onClick={()=>setConvertOpen(true)}>Convert quotation</Button>}</div>}</Card>
 <FormDrawer title="Convert approved quotation" open={convertOpen} width={620} onClose={()=>setConvertOpen(false)} onSubmit={()=>convertForm.submit()} loading={convert.isPending} okText="Create agreement draft">
  <Form form={convertForm} layout="vertical" onFinish={v=>convert.mutate(v)}
   initialValues={{effectiveDate:new Date().toISOString().slice(0,10),securityDeposit:0}}>
   <Form.Item name="quotationId" label="Approved quotation" rules={[{required:true}]}>
    <Select data-testid="approved-quotation-select" showSearch optionFilterProp="label" placeholder="Select an approved quotation"
     options={(approved.data??[]).map(q=>({value:q.id,label:`${q.quotationNumber} — ${q.partyName} — ${q.siteName}`}))}/>
   </Form.Item>
   <Form.Item name="templateId" label="Agreement design"
    extra="Native designs generate the final layout. Uploaded PDFs remain reference documents.">
    <Select allowClear placeholder="SteelFab standard design" options={(templates.data??[]).filter(t=>t.active).map(t=>({
     value:t.id,label:`${t.name} — ${t.renderingMode==='NATIVE'?'generates PDF':'reference only'}`
    }))}/>
   </Form.Item>
   <div className="master-form-grid">
    <Form.Item name="effectiveDate" label="Effective date" rules={[{required:true}]}><Input type="date"/></Form.Item>
    <Form.Item name="expiryDate" label="Expiry date"><Input type="date"/></Form.Item>
    <Form.Item name="securityDeposit" label="Security deposit" rules={[{required:true,type:'number',min:0}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item>
    <Form.Item name="notes" label="Notes"><Input.TextArea rows={2}/></Form.Item>
   </div>
  </Form>
 </FormDrawer>
 <FormDrawer mode="page" title={`Edit ${editing?.agreementNumber??''}`} subtitle="Review agreement dates, billing configuration, contracted quantities and rates." open={!!editing} width={920} onClose={()=>{if(form.isFieldsTouched())modal.confirm({title:'Discard unsaved changes?',onOk:()=>setEditing(undefined)});else setEditing(undefined);}} onSubmit={()=>form.submit()} loading={save.isPending} okText="Save changes">
  <Form form={form} layout="vertical" onFinish={v=>save.mutate(v)}><div className="master-form-grid"><Form.Item name="agreementDate" label="Agreement date" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="effectiveDate" label="Effective date" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="expiryDate" label="Expiry date"><Input type="date"/></Form.Item><Form.Item name="billingCycle" label="Billing cycle" rules={[{required:true}]}><Select options={['WEEKLY','MONTHLY','CUSTOM'].map(value=>({value,label:value}))}/></Form.Item><Form.Item noStyle shouldUpdate={(p,c)=>p.billingCycle!==c.billingCycle}>{()=>form.getFieldValue('billingCycle')==='CUSTOM'?<Form.Item name="customBillingCycleDays" label="Custom cycle days" rules={[{required:true,type:'number',min:1}]}><InputNumber min={1}/></Form.Item>:null}</Form.Item><NumberField name="gracePeriodDays" label="Grace days"/><NumberField name="minimumBillingDays" label="Minimum billing days"/><NumberField name="securityDeposit" label="Security deposit"/><Form.Item className="master-form-wide" name="terms" label="Terms"><Input.TextArea rows={3}/></Form.Item><Form.Item className="master-form-wide" name="notes" label="Notes"><Input.TextArea rows={2}/></Form.Item></div>
  <Form.List name="items">{fields=><Table pagination={false} rowKey="key" dataSource={fields} columns={[{title:'Item snapshot',render:(_,f)=><><Form.Item noStyle name={[f.name,'itemId']}><Input type="hidden"/></Form.Item><Form.Item noStyle name={[f.name,'itemName']}><Input readOnly/></Form.Item></>},{title:'Quantity',render:(_,f)=><Form.Item name={[f.name,'contractedQuantity']} rules={[{required:true,type:'number',min:.0001}]}><InputNumber min={.0001}/></Form.Item>},{title:'Rate',render:(_,f)=><Form.Item name={[f.name,'rate']} rules={[{required:true,type:'number',min:.0001,message:'Rate must be greater than 0'}]}><InputNumber min={.0001}/></Form.Item>},{title:'Loss / piece',render:(_,f)=><Form.Item name={[f.name,'lossRatePerPiece']}><InputNumber min={0}/></Form.Item>},{title:'Loss / weight',render:(_,f)=><Form.Item name={[f.name,'lossRatePerWeight']}><InputNumber min={0}/></Form.Item>},{title:'Damage',render:(_,f)=><Form.Item name={[f.name,'damageRate']}><InputNumber min={0}/></Form.Item>}]}/>}</Form.List></Form>
 </FormDrawer>
 <Modal title={selected?.agreementNumber} open={!!selected} width={1000} footer={null} onCancel={()=>setSelected(undefined)}>{selected&&<><Descriptions bordered column={2} items={[{key:'quote',label:'Source quotation',children:selected.sourceQuotationNumber},{key:'status',label:'Status',children:selected.status},{key:'party',label:'Party snapshot',children:<>{selected.partyName}<br/>{selected.partyGstin}<br/>{selected.partyAddress}</>},{key:'site',label:'Site snapshot',children:<>{selected.siteCode} — {selected.siteName}<br/>{selected.siteAddress}</>},{key:'dates',label:'Dates',children:`${selected.agreementDate} / ${selected.effectiveDate} / ${selected.expiryDate??'Open'}`},{key:'billing',label:'Billing',children:`${selected.billingCycle}; grace ${selected.gracePeriodDays} days`},{key:'total',label:'Grand total',children:money(selected.grandTotal)},{key:'deposit',label:'Security deposit',children:money(selected.securityDeposit)}]}/><Table style={{marginTop:16}} pagination={false} rowKey="id" dataSource={selected.items} columns={[{title:'Code',dataIndex:'itemCode'},{title:'Historical item',dataIndex:'itemName'},{title:'Size',dataIndex:'size'},{title:'Unit',dataIndex:'unit'},{title:'Quantity',dataIndex:'contractedQuantity'},{title:'Rate',dataIndex:'rate',render:money}]}/><Space style={{marginTop:16}}><AgreementActions agreement={selected} admin={admin} operations={operations} onView={()=>{}} onEdit={()=>edit(selected)} onAction={(n,r)=>act(selected,n,r)} onDownload={()=>void download(selected)} hideView/></Space></>}</Modal>
 </div>;
}
export function AgreementActions({agreement:a,admin,operations,onView,onEdit,onAction,onDownload,hideView=false}:{agreement:Agreement;admin:boolean;operations:boolean;onView:()=>void;onEdit:()=>void;onAction:(name:string,reason?:boolean)=>void;onDownload:()=>void;hideView?:boolean}){
 const writer=admin||operations;return <Space wrap>{!hideView&&<Button onClick={onView}>View</Button>}{writer&&a.status==='DRAFT'&&<Button data-testid="edit-agreement" onClick={onEdit}>Edit</Button>}{writer&&a.status==='DRAFT'&&<Button data-testid="ready-agreement" onClick={()=>onAction('ready-for-review')}>Ready for review</Button>}{writer&&a.status==='READY_FOR_REVIEW'&&<Button onClick={()=>onAction('return-to-draft',true)}>Return to draft</Button>}{writer&&['DRAFT','READY_FOR_REVIEW'].includes(a.status)&&<Button onClick={()=>onAction('generate-document')}>Generate PDF</Button>}{admin&&a.status==='READY_FOR_REVIEW'&&<Button type="primary" data-testid="activate-agreement" onClick={()=>onAction('activate')}>Activate</Button>}{admin&&a.status==='ACTIVE'&&<><Button onClick={()=>onAction('expire')}>Expire</Button><Button danger onClick={()=>onAction('terminate',true)}>Terminate</Button><Button onClick={()=>onAction('close')}>Close</Button></>}{admin&&['DRAFT','READY_FOR_REVIEW'].includes(a.status)&&<Button danger onClick={()=>onAction('cancel',true)}>Cancel</Button>}{a.generatedDocumentAttachmentId&&<Button icon={<DownloadOutlined/>} onClick={onDownload}>PDF</Button>}</Space>;
}
function NumberField({name,label}:{name:keyof Editor;label:string}){return <Form.Item name={name} label={label} rules={[{required:true,type:'number',min:0}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item>}
function label(v:string){return v.replaceAll('-',' ')}
function apiMessage(e:unknown){const data=(e as {response?:{data?:{code?:string;message?:string}}}).response?.data;return data?.code==='ACTIVE_AGREEMENT_ALREADY_EXISTS'?'Another active agreement already exists for this site.':data?.message??'Agreement operation failed';}
