import {fireEvent,render,screen} from '@testing-library/react';
import {describe,expect,it,vi} from 'vitest';
import type {Agreement} from '../types';
import {AgreementActions} from './AgreementsPage';
const agreement=(status:string,document=false):Agreement=>({id:1,agreementNumber:'AGR/2026-27/0001',sourceQuotationId:2,sourceQuotationNumber:'QT/2026-27/0001',partyId:1,partyName:'Party snapshot',siteId:1,siteName:'Site snapshot',siteCode:'SITE-1',agreementDate:'2026-07-26',effectiveDate:'2026-07-26',rentalType:'PER_PIECE_PER_DAY',billingCycle:'MONTHLY',gracePeriodDays:0,minimumBillingDays:0,status,securityDeposit:0,subtotal:100,discountAmount:0,taxableAmount:100,cgstAmount:9,sgstAmount:9,igstAmount:0,totalTax:18,transportCharge:0,loadingCharge:0,unloadingCharge:0,otherCharge:0,roundOff:0,grandTotal:118,items:[],version:0,...(document?{generatedDocumentAttachmentId:7}:{})});
const callbacks=()=>({onView:vi.fn(),onEdit:vi.fn(),onAction:vi.fn(),onDownload:vi.fn()});
describe('agreement workflow permissions',()=>{
 it('ADMIN sees draft workflow actions',()=>{render(<AgreementActions agreement={agreement('DRAFT')} admin operations={false} {...callbacks()}/>);expect(screen.getByRole('button',{name:'Edit'})).toBeVisible();expect(screen.getByRole('button',{name:'Ready for review'})).toBeVisible();expect(screen.getByRole('button',{name:'Cancel'})).toBeVisible();});
 it('OPERATIONS prepares but cannot activate',()=>{render(<AgreementActions agreement={agreement('READY_FOR_REVIEW')} admin={false} operations {...callbacks()}/>);expect(screen.getByRole('button',{name:'Generate PDF'})).toBeVisible();expect(screen.queryByRole('button',{name:'Activate'})).not.toBeInTheDocument();});
 it('ACCOUNTS and VIEWER remain read-only',()=>{render(<AgreementActions agreement={agreement('DRAFT')} admin={false} operations={false} {...callbacks()}/>);expect(screen.getByRole('button',{name:'View'})).toBeVisible();expect(screen.queryByRole('button',{name:'Edit'})).not.toBeInTheDocument();});
 it('ACTIVE is read-only and ADMIN sees lifecycle actions',()=>{render(<AgreementActions agreement={agreement('ACTIVE',true)} admin operations={false} {...callbacks()}/>);expect(screen.queryByRole('button',{name:'Edit'})).not.toBeInTheDocument();['Expire','Terminate','Close'].forEach(name=>expect(screen.getByRole('button',{name})).toBeVisible());expect(screen.getByRole('button',{name:/PDF/})).toBeVisible();});
 it('termination delegates a required reason',()=>{const cb=callbacks();render(<AgreementActions agreement={agreement('ACTIVE')} admin operations={false} {...cb}/>);fireEvent.click(screen.getByRole('button',{name:'Terminate'}));expect(cb.onAction).toHaveBeenCalledWith('terminate',true);});
 it('generated PDF invokes download',()=>{const cb=callbacks();render(<AgreementActions agreement={agreement('READY_FOR_REVIEW',true)} admin={false} operations={false} {...cb}/>);fireEvent.click(screen.getByRole('button',{name:/PDF/}));expect(cb.onDownload).toHaveBeenCalledOnce();});
});
