CREATE TABLE receiving_challans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    receiving_challan_number VARCHAR(50) NOT NULL,
    agreement_id BIGINT NULL,
    party_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    linked_issued_challan_id BIGINT NULL,
    receive_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    vehicle_number VARCHAR(50) NULL,
    driver_name VARCHAR(100) NULL,
    driver_phone VARCHAR(20) NULL,
    transporter_id BIGINT NULL,
    source_type VARCHAR(30) NOT NULL,
    notes VARCHAR(1000) NULL,
    posted_at TIMESTAMP(6) NULL,
    posted_by VARCHAR(50) NULL,
    cancelled_at TIMESTAMP(6) NULL,
    cancelled_by VARCHAR(50) NULL,
    cancellation_reason VARCHAR(255) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(50) NOT NULL,
    CONSTRAINT uk_receiving_challans_number UNIQUE (receiving_challan_number),
    CONSTRAINT fk_receiving_challans_party FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_receiving_challans_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_receiving_challans_agreement FOREIGN KEY (agreement_id) REFERENCES agreements(id),
    CONSTRAINT fk_receiving_challans_issued FOREIGN KEY (linked_issued_challan_id) REFERENCES issued_challans(id)
);

CREATE TABLE receiving_challan_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    receiving_challan_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    linked_issued_challan_item_id BIGINT NULL,
    opening_import_transaction_id BIGINT NULL,
    item_code_snapshot VARCHAR(50) NOT NULL,
    item_name_snapshot VARCHAR(255) NOT NULL,
    size_snapshot VARCHAR(50) NULL,
    unit_snapshot VARCHAR(20) NOT NULL,
    pending_quantity_snapshot DECIMAL(19,4) NOT NULL,
    good_returned_quantity DECIMAL(19,4) NOT NULL DEFAULT 0,
    damaged_returned_quantity DECIMAL(19,4) NOT NULL DEFAULT 0,
    lost_quantity DECIMAL(19,4) NOT NULL DEFAULT 0,
    extra_returned_quantity DECIMAL(19,4) NOT NULL DEFAULT 0,
    exchanged_from_item_id BIGINT NULL,
    exchanged_to_item_id BIGINT NULL,
    exchanged_quantity DECIMAL(19,4) NOT NULL DEFAULT 0,
    weight_per_piece_snapshot DECIMAL(19,4) NULL,
    good_returned_weight DECIMAL(19,4) NOT NULL DEFAULT 0,
    damaged_weight DECIMAL(19,4) NOT NULL DEFAULT 0,
    lost_weight DECIMAL(19,4) NOT NULL DEFAULT 0,
    notes VARCHAR(255) NULL,
    sequence INT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_receiving_items_challan FOREIGN KEY (receiving_challan_id) REFERENCES receiving_challans(id),
    CONSTRAINT fk_receiving_items_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_receiving_items_issued_item FOREIGN KEY (linked_issued_challan_item_id) REFERENCES issued_challan_items(id),
    CONSTRAINT fk_receiving_items_exchanged_from FOREIGN KEY (exchanged_from_item_id) REFERENCES items(id),
    CONSTRAINT fk_receiving_items_exchanged_to FOREIGN KEY (exchanged_to_item_id) REFERENCES items(id)
);
