CREATE TABLE client_inquiries (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    inquiry_number VARCHAR(50) NULL UNIQUE,
    inquiry_date DATE NOT NULL,
    source VARCHAR(20) NOT NULL,
    contact_name VARCHAR(150) NOT NULL,
    phone VARCHAR(30) NULL,
    email VARCHAR(150) NULL,
    party_id BIGINT NULL,
    site_id BIGINT NULL,
    requirement VARCHAR(2000) NOT NULL,
    follow_up_date DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    quotation_id BIGINT NULL,
    notes VARCHAR(1000) NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_inquiry_party FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_inquiry_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_inquiry_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id),
    CONSTRAINT chk_inquiry_source CHECK (source IN ('EMAIL','PHONE','JUSTDIAL','REFERENCE','WALK_IN','OTHER')),
    CONSTRAINT chk_inquiry_status CHECK (status IN ('OPEN','FOLLOW_UP','QUOTED','WON','LOST','CANCELLED'))
);

CREATE TABLE site_operations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    operation_number VARCHAR(50) NULL UNIQUE,
    operation_date DATE NOT NULL,
    operation_type VARCHAR(30) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    party_id BIGINT NULL,
    site_id BIGINT NOT NULL,
    issued_challan_id BIGINT NULL,
    receiving_challan_id BIGINT NULL,
    provider_type VARCHAR(30) NULL,
    provider_name VARCHAR(150) NULL,
    transporter_name VARCHAR(150) NULL,
    vehicle_number VARCHAR(50) NULL,
    driver_name VARCHAR(100) NULL,
    worker_count INT NULL,
    quantity DECIMAL(19,4) NULL,
    rate DECIMAL(19,2) NOT NULL DEFAULT 0,
    amount DECIMAL(19,2) NOT NULL DEFAULT 0,
    charge_to_client BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',
    reference_number VARCHAR(100) NULL,
    notes VARCHAR(1000) NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_site_operation_party FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_site_operation_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_site_operation_issued FOREIGN KEY (issued_challan_id) REFERENCES issued_challans(id),
    CONSTRAINT fk_site_operation_receiving FOREIGN KEY (receiving_challan_id) REFERENCES receiving_challans(id),
    CONSTRAINT chk_site_operation_type CHECK (operation_type IN ('TRANSPORT','LOADING_LABOUR','UNLOADING_LABOUR','MATHADI','TPI','CONTRACT_LABOUR','SITE_EXPENSE')),
    CONSTRAINT chk_site_operation_direction CHECK (direction IN ('DELIVERY','RETURN','GENERAL')),
    CONSTRAINT chk_site_operation_status CHECK (status IN ('PLANNED','CONFIRMED','COMPLETED','CANCELLED')),
    CONSTRAINT chk_site_operation_amount CHECK (amount >= 0 AND rate >= 0)
);

ALTER TABLE sites ADD COLUMN excel_template_code VARCHAR(50) NULL;
