import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { apiClient, apiErrorMessage } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { AppButton, Card, DateField, EmptyBlock, PageHeader, StatusPill } from '../components/ui';
import { colors, fonts } from '../theme';

type EligibleAgreement={id:number;agreementNumber:string;partyName:string;siteName:string;effectiveDate:string;expiryDate?:string};
type Segment={id:number;itemCode:string;itemName:string;quantity:number;billableDays:number;baseRate:number;rentalType:string;amount:number;sourceIssueReference:string;sourceEndReference?:string};
type Run={id:number;billingRunNumber:string;agreementNumber:string;partyName:string;siteName:string;periodStart:string;periodEnd:string;status:'DRAFT'|'CALCULATED'|'FINALIZED'|'CANCELLED';rentalSubtotal:number;taxableAmount:number;totalTax:number;grandTotal:number;segments:Segment[];charges:{id:number;selected:boolean;description:string;amount:number}[]};
type Page<T>={content:T[]};
const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(value||0);

export function BillingScreen(){
  const insets=useSafeAreaInsets();
  const {user}=useAuth();
  const canPrepare=user?.roles.some(role=>['ROLE_ADMIN','ROLE_ACCOUNTS','ROLE_OPERATIONS'].includes(role))??false;
  const canFinalize=user?.roles.some(role=>['ROLE_ADMIN','ROLE_ACCOUNTS'].includes(role))??false;
  const [agreements,setAgreements]=useState<EligibleAgreement[]>([]),[runs,setRuns]=useState<Run[]>([]);
  const [agreement,setAgreement]=useState<EligibleAgreement>(),[start,setStart]=useState(''),[end,setEnd]=useState('');
  const [selected,setSelected]=useState<Run>(),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,r]=await Promise.all([apiClient.get<EligibleAgreement[]>('/billing-runs/eligible-agreements'),apiClient.get<Page<Run>>('/billing-runs',{params:{size:50,sort:'id,desc'}})]);setAgreements(a.data);setRuns(r.data.content);}catch(cause){setError(apiErrorMessage(cause,'Unable to load monthly billing.'));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const choose=async(value:EligibleAgreement)=>{setAgreement(value);try{const response=await apiClient.get<{periodStart:string;periodEnd:string}>(`/billing-runs/agreement/${value.id}/suggested-period`);setStart(response.data.periodStart);setEnd(response.data.periodEnd);}catch(cause){setError(apiErrorMessage(cause,'Unable to suggest the next billing period.'));}};
  const open=async(id:number)=>{try{setSelected((await apiClient.get<Run>(`/billing-runs/${id}`)).data);}catch(cause){setError(apiErrorMessage(cause,'Unable to load billing details.'));}};
  const create=async()=>{if(!agreement||!start||!end)return;setLoading(true);try{const run=(await apiClient.post<Run>('/billing-runs',{agreementId:agreement.id,periodStart:start,periodEnd:end})).data;setAgreement(undefined);setSelected(run);await load();}catch(cause){setError(apiErrorMessage(cause,'Unable to prepare this billing period.'));}finally{setLoading(false);}};
  const finalize=()=>selected&&Alert.alert('Finalize rental bill?',`This locks ${selected.billingRunNumber} and its challan timeline.`,[{text:'Cancel',style:'cancel'},{text:'Finalize',onPress:async()=>{try{setSelected((await apiClient.post<Run>(`/billing-runs/${selected.id}/finalize`)).data);await load();}catch(cause){setError(apiErrorMessage(cause,'Unable to finalize this bill.'));}}}]);
  const invoice=async()=>{if(!selected)return;try{const result=(await apiClient.post<{id:number;invoiceNumber:string}>('/invoices/from-billing-run/'+selected.id)).data;Alert.alert('Invoice created',`${result.invoiceNumber} is ready in Invoices on the web portal.`);}catch(cause){setError(apiErrorMessage(cause,'Unable to create the invoice.'));}};
  return <ScrollView style={styles.page} contentContainerStyle={{paddingTop:insets.top+18,paddingBottom:36}} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}>
    <PageHeader eyebrow="Accounts" title="Monthly rental billing"/>
    <Text style={styles.lead}>Rent starts from posted issued challans and stops when material is returned. Review the calculated timeline before invoicing.</Text>
    {error?<Text style={styles.error}>{error}</Text>:null}
    {canPrepare?<Card style={styles.section}><Text style={styles.title}>1. Choose agreement</Text>{agreements.length?agreements.map(row=><Pressable key={row.id} style={[styles.choice,agreement?.id===row.id&&styles.choiceActive]} onPress={()=>void choose(row)}><Text style={styles.choiceTitle}>{row.agreementNumber}</Text><Text style={styles.meta}>{row.partyName} | {row.siteName}</Text></Pressable>):<EmptyBlock title="No agreement ready" message="Activate an agreement before preparing monthly rent."/>}{agreement?<View style={styles.dates}><DateField label="Period start" value={start} onChange={setStart}/><DateField label="Period end" value={end} onChange={setEnd} maximumDate={new Date()}/><AppButton title="Calculate rental" onPress={()=>void create()} loading={loading} disabled={!start||!end}/></View>:null}</Card>:null}
    <Text style={styles.listTitle}>Billing history</Text>
    {!runs.length?<EmptyBlock title="No billing runs" message="The first prepared rental period will appear here."/>:runs.map(run=><Pressable key={run.id} onPress={()=>void open(run.id)}><Card style={styles.run}><View style={styles.row}><View style={styles.flex}><Text style={styles.choiceTitle}>{run.billingRunNumber}</Text><Text style={styles.meta}>{run.partyName} | {run.siteName}</Text><Text style={styles.meta}>{run.periodStart} to {run.periodEnd}</Text></View><StatusPill value={run.status}/></View><Text style={styles.amount}>{money(run.grandTotal)}</Text></Card></Pressable>)}
    {selected?<Card style={styles.detail}><View style={styles.row}><Text style={styles.title}>2. Review calculation</Text><Pressable onPress={()=>setSelected(undefined)}><Text style={styles.link}>Close</Text></Pressable></View><Text style={styles.meta}>{selected.agreementNumber} | {selected.periodStart} to {selected.periodEnd}</Text>{!selected.segments.length?<EmptyBlock title="No billable material" message="No issued material was deployed in this period. This run cannot be finalized at zero."/>:selected.segments.map(line=><View key={line.id} style={styles.line}><Text style={styles.choiceTitle}>{line.itemCode} - {line.itemName}</Text><Text style={styles.meta}>{line.quantity} units | {line.billableDays} days | {line.rentalType==='PER_PIECE_PER_MONTH'?'monthly rate':'daily rate'} {money(line.baseRate)}</Text><Text style={styles.meta}>From {line.sourceIssueReference}{line.sourceEndReference?` to ${line.sourceEndReference}`:'; still at site'}</Text><Text style={styles.lineAmount}>{money(line.amount)}</Text></View>)}<View style={styles.total}><Text style={styles.meta}>Taxable {money(selected.taxableAmount)} + tax {money(selected.totalTax)}</Text><Text style={styles.amount}>{money(selected.grandTotal)}</Text></View>{canFinalize&&selected.status==='CALCULATED'?<AppButton title="Finalize billing run" onPress={finalize} disabled={selected.grandTotal<=0}/>:null}{canFinalize&&selected.status==='FINALIZED'?<AppButton title="Create SteelFab invoice" onPress={()=>void invoice()}/>:null}</Card>:null}
  </ScrollView>;
}

const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas,paddingHorizontal:18},lead:{color:colors.muted,lineHeight:20,marginBottom:14},error:{color:colors.red,marginBottom:12,fontFamily:fonts.semiBold},section:{marginBottom:20},title:{color:colors.ink,fontSize:17,fontFamily:fonts.bold,marginBottom:10},choice:{borderWidth:1,borderColor:colors.line,borderRadius:8,padding:12,marginTop:8},choiceActive:{borderColor:colors.primary,backgroundColor:colors.primarySoft},choiceTitle:{color:colors.ink,fontFamily:fonts.bold},meta:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:3},dates:{gap:14,marginTop:16},listTitle:{color:colors.ink,fontSize:20,fontFamily:fonts.extraBold,marginBottom:10},run:{marginBottom:10},row:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10},flex:{flex:1},amount:{color:colors.ink,fontSize:22,fontFamily:fonts.extraBold,marginTop:12},detail:{marginTop:12},link:{color:colors.primary,fontFamily:fonts.bold},line:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},lineAmount:{color:colors.primaryDark,fontFamily:fonts.bold,marginTop:6},total:{paddingVertical:16,alignItems:'flex-end',gap:2}});
