import {useState} from 'react';
import {App,Button,Card,Checkbox,Form,Input,InputNumber,Modal,Select,Space,Table,Tabs,Tag} from 'antd';
import {DownloadOutlined,PlusOutlined,SearchOutlined} from '@ant-design/icons';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '../../../api/client';

type Page<T>={content:T[]};type Option={id:number;legalName?:string;partyName?:string;siteName?:string};
type Inquiry={id:number;inquiryNumber:string;inquiryDate:string;source:string;contactName:string;phone?:string;email?:string;partyId?:number;partyName?:string;siteId?:number;siteName?:string;requirement:string;followUpDate?:string;status:string;quotationId?:number;quotationNumber?:string;notes?:string};
type Operation={id:number;operationNumber:string;operationDate:string;operationType:string;direction:string;partyId?:number;partyName?:string;siteId:number;siteName:string;issuedChallanId?:number;receivingChallanId?:number;providerType?:string;providerName?:string;transporterName?:string;vehicleNumber?:string;driverName?:string;workerCount?:number;quantity?:number;rate:number;amount:number;chargeToClient:boolean;status:string;referenceNumber?:string;notes?:string};
const today=()=>new Date().toISOString().slice(0,10),human=(v:string)=>v.replaceAll('_',' ');
const inquirySources=['EMAIL','PHONE','JUSTDIAL','REFERENCE','WALK_IN','OTHER'];
const inquiryStatuses=['OPEN','FOLLOW_UP','QUOTED','WON','LOST','CANCELLED'];
const operationTypes=['TRANSPORT','LOADING_LABOUR','UNLOADING_LABOUR','MATHADI','TPI','CONTRACT_LABOUR','SITE_EXPENSE'];
const operationStatuses=['PLANNED','CONFIRMED','COMPLETED','CANCELLED'];

export function ClientWorkflowPage(){
 const {message}=App.useApp(),qc=useQueryClient(),[search,setSearch]=useState(''),[exportSiteId,setExportSiteId]=useState<number>(),[exporting,setExporting]=useState(false),[inquiryOpen,setInquiryOpen]=useState(false),[operationOpen,setOperationOpen]=useState(false),[editingInquiry,setEditingInquiry]=useState<Inquiry>(),[editingOperation,setEditingOperation]=useState<Operation>();
 const [inquiryForm]=Form.useForm(),[operationForm]=Form.useForm();
 const inquiries=useQuery({queryKey:['client-inquiries',search],queryFn:async()=>(await apiClient.get<Inquiry[]>('/client-workflow/inquiries',{params:{search}})).data});
 const operations=useQuery({queryKey:['site-operations'],queryFn:async()=>(await apiClient.get<Operation[]>('/client-workflow/operations')).data});
 const parties=useQuery({queryKey:['workflow-parties'],queryFn:async()=>(await apiClient.get<Page<Option>>('/parties',{params:{size:500}})).data.content});
 const sites=useQuery({queryKey:['workflow-sites'],queryFn:async()=>(await apiClient.get<Page<Option>>('/sites',{params:{size:500}})).data.content});
 const refresh=()=>{void qc.invalidateQueries({queryKey:['client-inquiries']});void qc.invalidateQueries({queryKey:['site-operations']});};
 const saveInquiry=useMutation({mutationFn:async(v:Inquiry)=>editingInquiry?(await apiClient.put(`/client-workflow/inquiries/${editingInquiry.id}`,v)).data:(await apiClient.post('/client-workflow/inquiries',v)).data,onSuccess:()=>{message.success('Inquiry saved');setInquiryOpen(false);setEditingInquiry(undefined);inquiryForm.resetFields();refresh();},onError:()=>message.error('Unable to save inquiry')});
 const saveOperation=useMutation({mutationFn:async(v:Operation)=>editingOperation?(await apiClient.put(`/client-workflow/operations/${editingOperation.id}`,v)).data:(await apiClient.post('/client-workflow/operations',v)).data,onSuccess:()=>{message.success('Operation saved');setOperationOpen(false);setEditingOperation(undefined);operationForm.resetFields();refresh();},onError:()=>message.error('Unable to save operation')});
 const editInquiry=(row?:Inquiry)=>{setEditingInquiry(row);inquiryForm.setFieldsValue(row??{inquiryDate:today(),source:'PHONE',status:'OPEN'});setInquiryOpen(true)};
 const editOperation=(row?:Operation)=>{setEditingOperation(row);operationForm.setFieldsValue(row??{operationDate:today(),operationType:'TRANSPORT',direction:'DELIVERY',rate:0,amount:0,chargeToClient:false,status:'PLANNED'});setOperationOpen(true)};
 const exportSbut=async()=>{if(!exportSiteId)return;setExporting(true);try{const response=await apiClient.get<Blob>(`/reports/sites/${exportSiteId}/sbut-dr.xlsx`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=`SBUT-D-R-${today()}.xlsx`;anchor.click();URL.revokeObjectURL(url);message.success('SBUT workbook downloaded');}catch{message.error('Assign the SBUT D&R format to this site before exporting');}finally{setExporting(false)}};
 return <div className="page-stack"><div className="page-header-container"><div><h1 className="page-heading">Client Workflow</h1><p className="page-description">Track inquiries, transport, labour and site expenses from first contact through return.</p></div></div>
 <Tabs items={[
  {key:'inquiries',label:'Inquiries',children:<Card><Space wrap style={{marginBottom:16}}><Input prefix={<SearchOutlined/>} placeholder="Search inquiries" allowClear value={search} onChange={e=>setSearch(e.target.value)}/><Button type="primary" icon={<PlusOutlined/>} onClick={()=>editInquiry()}>New inquiry</Button></Space><Table rowKey="id" loading={inquiries.isLoading} dataSource={inquiries.data} pagination={{pageSize:20}} onRow={row=>({onDoubleClick:()=>editInquiry(row)})} columns={[{title:'Inquiry',dataIndex:'inquiryNumber'},{title:'Date',dataIndex:'inquiryDate'},{title:'Source',dataIndex:'source',render:human},{title:'Contact',render:(_,r)=><>{r.contactName}<br/><small>{r.phone}</small></>},{title:'Party / site',render:(_,r)=>`${r.partyName??'-'} / ${r.siteName??'-'}`},{title:'Requirement',dataIndex:'requirement',ellipsis:true},{title:'Follow-up',dataIndex:'followUpDate'},{title:'Status',dataIndex:'status',render:s=><Tag>{human(s)}</Tag>},{title:'Quotation',dataIndex:'quotationNumber'},{title:'',render:(_,r)=><Button onClick={()=>editInquiry(r)}>Edit</Button>}]}/></Card>},
  {key:'operations',label:'Transport, Labour & Expenses',children:<Card><Space wrap style={{marginBottom:16}}><Button type="primary" icon={<PlusOutlined/>} onClick={()=>editOperation()}>New operation</Button><Select showSearch optionFilterProp="label" placeholder="Site for SBUT workbook" value={exportSiteId} onChange={setExportSiteId} style={{minWidth:260}} options={(sites.data??[]).map(s=>({value:s.id,label:`${s.siteName} - ${s.partyName}`}))}/><Button icon={<DownloadOutlined/>} disabled={!exportSiteId} loading={exporting} onClick={()=>void exportSbut()}>SBUT D&amp;R Excel</Button></Space><Table rowKey="id" loading={operations.isLoading} dataSource={operations.data} pagination={{pageSize:20}} columns={[{title:'Reference',dataIndex:'operationNumber'},{title:'Date',dataIndex:'operationDate'},{title:'Type',dataIndex:'operationType',render:human},{title:'Direction',dataIndex:'direction',render:human},{title:'Site',dataIndex:'siteName'},{title:'Provider / vehicle',render:(_,r)=>r.transporterName||r.providerName||r.vehicleNumber||'-'},{title:'Amount',dataIndex:'amount',render:v=>`INR ${Number(v).toLocaleString('en-IN')}`},{title:'Client charge',dataIndex:'chargeToClient',render:v=><Tag color={v?'green':'default'}>{v?'Yes':'No'}</Tag>},{title:'Status',dataIndex:'status',render:s=><Tag>{human(s)}</Tag>},{title:'',render:(_,r)=><Button onClick={()=>editOperation(r)}>Edit</Button>}]}/></Card>}
 ]}/>
 <Modal open={inquiryOpen} title={editingInquiry?'Edit inquiry':'New inquiry'} okText="Save inquiry" onOk={()=>inquiryForm.submit()} confirmLoading={saveInquiry.isPending} onCancel={()=>setInquiryOpen(false)} width={760}><Form form={inquiryForm} layout="vertical" onFinish={v=>saveInquiry.mutate(v)}><div className="master-form-grid"><Form.Item name="inquiryDate" label="Inquiry date" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="source" label="Source" rules={[{required:true}]}><Select options={inquirySources.map(value=>({value,label:human(value)}))}/></Form.Item><Form.Item name="contactName" label="Contact name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="phone" label="Phone"><Input/></Form.Item><Form.Item name="email" label="Email"><Input type="email"/></Form.Item><Form.Item name="partyId" label="Party"><Select allowClear showSearch optionFilterProp="label" options={(parties.data??[]).map(p=>({value:p.id,label:p.legalName}))}/></Form.Item><Form.Item name="siteId" label="Site"><Select allowClear showSearch optionFilterProp="label" options={(sites.data??[]).map(s=>({value:s.id,label:`${s.siteName} — ${s.partyName}`}))}/></Form.Item><Form.Item name="followUpDate" label="Follow-up date"><Input type="date"/></Form.Item><Form.Item name="status" label="Status" rules={[{required:true}]}><Select options={inquiryStatuses.map(value=>({value,label:human(value)}))}/></Form.Item><Form.Item name="quotationId" label="Linked quotation ID"><InputNumber min={1} style={{width:'100%'}}/></Form.Item><Form.Item className="master-form-wide" name="requirement" label="Requirement" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Form.Item className="master-form-wide" name="notes" label="Notes"><Input.TextArea rows={2}/></Form.Item></div></Form></Modal>
 <Modal open={operationOpen} title={editingOperation?'Edit operation':'New operation'} okText="Save operation" onOk={()=>operationForm.submit()} confirmLoading={saveOperation.isPending} onCancel={()=>setOperationOpen(false)} width={850}><Form form={operationForm} layout="vertical" onFinish={v=>saveOperation.mutate(v)}><div className="master-form-grid"><Form.Item name="operationDate" label="Date" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="operationType" label="Type" rules={[{required:true}]}><Select options={operationTypes.map(value=>({value,label:human(value)}))}/></Form.Item><Form.Item name="direction" label="Direction" rules={[{required:true}]}><Select options={['DELIVERY','RETURN','GENERAL'].map(value=>({value,label:human(value)}))}/></Form.Item><Form.Item name="siteId" label="Site" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(sites.data??[]).map(s=>({value:s.id,label:`${s.siteName} — ${s.partyName}`}))}/></Form.Item><Form.Item name="partyId" label="Party"><Select allowClear showSearch optionFilterProp="label" options={(parties.data??[]).map(p=>({value:p.id,label:p.legalName}))}/></Form.Item><Form.Item name="issuedChallanId" label="Delivery challan ID"><InputNumber min={1} style={{width:'100%'}}/></Form.Item><Form.Item name="receivingChallanId" label="Return challan ID"><InputNumber min={1} style={{width:'100%'}}/></Form.Item><Form.Item name="providerType" label="Provider type"><Input placeholder="Mathadi / TPI / contractor"/></Form.Item><Form.Item name="providerName" label="Provider name"><Input/></Form.Item><Form.Item name="transporterName" label="Transporter"><Input/></Form.Item><Form.Item name="vehicleNumber" label="Vehicle number"><Input/></Form.Item><Form.Item name="driverName" label="Driver"><Input/></Form.Item><Form.Item name="workerCount" label="Workers"><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="quantity" label="Quantity / hours"><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="rate" label="Rate" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="amount" label="Amount" rules={[{required:true}]}><InputNumber min={0} style={{width:'100%'}}/></Form.Item><Form.Item name="status" label="Status" rules={[{required:true}]}><Select options={operationStatuses.map(value=>({value,label:human(value)}))}/></Form.Item><Form.Item name="referenceNumber" label="External reference"><Input/></Form.Item><Form.Item name="chargeToClient" valuePropName="checked"><Checkbox>Charge this amount to client</Checkbox></Form.Item><Form.Item className="master-form-wide" name="notes" label="Notes"><Input.TextArea rows={2}/></Form.Item></div></Form></Modal>
 </div>;
}
