export type BillingRunSegment = {
  id: number;
  agreementItemId: number;
  itemId: number;
  itemCode: string;
  itemName: string;
  size?: string;
  unit: string;
  weight?: number;
  sourceIssueReference: string;
  sourceEndReference?: string;
  rentalType: string;
  quantity: number;
  area?: number;
  weightVal?: number;
  segmentStart: string;
  segmentEnd: string;
  billableDays: number;
  baseRate: number;
  appliedSlab?: string;
  amount: number;
  calculationExplanation: string;
  sequenceNumber: number;
};

export type BillingRunCharge = {
  id: number;
  sourceType: string;
  sourceId: number;
  sourceDocumentNumber: string;
  chargeType: string;
  description: string;
  quantity: number;
  rate: number;
  amount: number;
  taxable: boolean;
  selected: boolean;
};

export type BillingRun = {
  id: number;
  billingRunNumber: string;
  agreementId: number;
  agreementNumber: string;
  partyId: number;
  partyName: string;
  siteId: number;
  siteName: string;
  periodStart: string;
  periodEnd: string;
  status: 'DRAFT' | 'CALCULATED' | 'FINALIZED' | 'CANCELLED';
  rentalSubtotal: number;
  lossChargeTotal: number;
  damageChargeTotal: number;
  operationalChargeTotal: number;
  manualAdjustmentTotal: number;
  discountType: 'NONE' | 'PERCENTAGE' | 'FIXED';
  discountValue: number;
  discountAmount: number;
  taxableAmount: number;
  cgstRate: number;
  cgstAmount: number;
  sgstRate: number;
  sgstAmount: number;
  igstRate: number;
  igstAmount: number;
  totalTax: number;
  roundOff: number;
  grandTotal: number;
  calculatedAt?: string;
  calculatedBy?: string;
  finalizedAt?: string;
  finalizedBy?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  version: number;
  segments: BillingRunSegment[];
  charges: BillingRunCharge[];
};

export type InvoiceItem = {
  id: number;
  lineType: string;
  agreementItemId?: number;
  sourceType?: string;
  sourceId?: number;
  sourceDocumentNumber?: string;
  itemId?: number;
  itemCodeSnapshot?: string;
  itemNameSnapshot?: string;
  sizeSnapshot?: string;
  unitSnapshot?: string;
  description: string;
  quantity: number;
  area?: number;
  weight?: number;
  billableDays?: number;
  rate: number;
  taxable: boolean;
  amount: number;
  sequenceNumber: number;
};

export type Invoice = {
  id: number;
  invoiceNumber: string;
  billingRunId: number;
  billingRunNumber: string;
  agreementId: number;
  agreementNumberSnapshot: string;
  partyNameSnapshot: string;
  partyGstinSnapshot?: string;
  partyAddressSnapshot: string;
  partyStateSnapshot: string;
  siteNameSnapshot: string;
  siteCodeSnapshot: string;
  siteAddressSnapshot: string;
  invoiceDate: string;
  dueDate: string;
  periodStart: string;
  periodEnd: string;
  status: 'DRAFT' | 'ISSUED' | 'CANCELLED';
  subtotal: number;
  discountAmount: number;
  taxableAmount: number;
  cgstRate: number;
  cgstAmount: number;
  sgstRate: number;
  sgstAmount: number;
  igstRate: number;
  igstAmount: number;
  totalTax: number;
  roundOff: number;
  grandTotal: number;
  terms?: string;
  notes?: string;
  generatedPdfAttachmentId?: number;
  issuedAt?: string;
  issuedBy?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  version: number;
  items: InvoiceItem[];
};
